const GAME_STATES = {
    SET_USERNAME: 1,
    READY: 2,
    SETUP: 3,
    SELECT_ANSWER: 4,
    WAITING: 5,
    SCOREBOARD: 6,
    GAME_OVER: 7,
    PLAY_AGAIN: 8,
    SELECT_GAME: 9,
};

const REFRESH_FREQUENCY_MINUTES = 55;
const MAX_ATTEMPTS = 5;
const CONNECTION_HEARTBEAT_MS = 30000;
const CONNECTION_RECONNECT_GRACE_MS = 45000;
const ROUND_ANSWER_TIMEOUT_MS = 30000;
const GAME_OVER_DISPLAY_MS = 5000;
const SPOTIFY_MIN_ROUNDS = 1;
const SPOTIFY_DEFAULT_ROUNDS = 5;
const SPOTIFY_MAX_ROUNDS = 50;
const SPOTIFY_RETRY_ATTEMPTS = 2;
const SPOTIFY_RETRY_DELAY_MS = 1000;
module.exports = {
    GAME_STATES,
    REFRESH_FREQUENCY_MINUTES,
    MAX_ATTEMPTS,
    CONNECTION_HEARTBEAT_MS,
    CONNECTION_RECONNECT_GRACE_MS,
    ROUND_ANSWER_TIMEOUT_MS,
    GAME_OVER_DISPLAY_MS,
    SPOTIFY_MIN_ROUNDS,
    SPOTIFY_DEFAULT_ROUNDS,
    SPOTIFY_MAX_ROUNDS,
    SPOTIFY_RETRY_ATTEMPTS,
    SPOTIFY_RETRY_DELAY_MS,
};
