const GAME_STATES = {
    SET_USERNAME: 1,
    READY: 2,
    SETUP: 3,
    SELECT_ANSWER: 4,
    WAITING: 5,
    SCOREBOARD: 6,
    GAME_OVER: 7,
    PLAY_AGAIN: 8,
    SELECT_GAME: 9,
};

const REFRESH_FREQUENCY_MINUTES = 55;
const MAX_ATTEMPTS = 100;
const CONNECTION_HEARTBEAT_MS = 30000;
const SPOTIFY_RETRY_ATTEMPTS = 2;
const SPOTIFY_RETRY_DELAY_MS = 1000;
module.exports = {
    GAME_STATES,
    REFRESH_FREQUENCY_MINUTES,
    MAX_ATTEMPTS,
    CONNECTION_HEARTBEAT_MS,
    SPOTIFY_RETRY_ATTEMPTS,
    SPOTIFY_RETRY_DELAY_MS,
};
